alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -l'
alias ls='ls --color=auto'
alias alpha='mpv http://194.219.46.2:8080/live'
alias real='mpv http://realfm.live24.gr/realfm'
alias skai='mpv http://netradio.live24.gr/skai1003'
alias 984='mpv http://athina984.live24.gr/athina984'
alias vima='mpv http://vimafm.live24.gr:80/vimafm'

